added cinic10-dataset
sbrodehl/tf-boilerplate pull request #8
Opened 2019-07-16 14:47 UTC by da-h

Hi,

this PR adds the [**CINIC-10**](https://www.bayeswatch.com/2018/10/09/CINIC) to *tf-boilerplate*.

As the other scripts, this script
- downloads the tar-file
- extracts all contents
- converts the png-files to tfrecords

Best
*da-h*

2019-07-16 20:15 UTC, sbrodehl requested changes
Thanks for the contribution!
The cinic-10 dataset would be a great addition to the project.

Please review the suggested changes.

2019-07-16 20:15 UTC, sbrodehl commented on data/cinic10/__init__.py
> +class Cifar10DataSet(object):
The class name needs to be changes.
```suggestion
class Cinic10DataSet(object):
```

2019-07-16 20:15 UTC, sbrodehl commented on data/cinic10/__init__.py
> +from .generate_cifar10_tfrecords import main as download
is `generate_cifar10_tfrecords` correct?

2019-07-16 20:15 UTC, sbrodehl commented on data/cinic10/__init__.py
> +        return Cifar10DataSet(self.data_dir, subset='train', use_distortion=False).make_batch()
Needs to be changed as well
```suggestion
        return Cinic10DataSet(self.data_dir, subset='train', use_distortion=False).make_batch()
```

2019-07-16 20:15 UTC, sbrodehl commented on data/cinic10/__init__.py
> +        return Cifar10DataSet(self.data_dir, subset='eval', use_distortion=False).make_batch()
Needs to be changed as well
```suggestion
        return Cinic10DataSet(self.data_dir, subset='eval', use_distortion=False).make_batch()
```

2019-07-17 06:52 UTC, da-h commented
Hi,

I cleaned up the commit, adding the changes that you suggested.

Best
*da-h*

2019-07-17 06:52 UTC, merged

2019-07-17 10:04 UTC, sbrodehl commented
Thank you!